### ISSUE TITLE
ohp!

### ISSUE THREAD

**Issue by xiaoxiong007** [PacktPublishing/Hands-On-Python-Deep-Learning-for-Web#10]
this code is so old,i can even not use tf.keras  but only keras

**Comment by xprilion** [comment]
Hey @xiaoxiong007, thanks for reaching out on this! Most of the book's chapter codes were written before TF 2.0 was introduced. We'll be updating that when (and if it comes) in the next update of the book. 

However, if you could let know which chapters you're looking at, maybe we can point you to some new code implementation of the same. However, you'd have to make the connection with the changes brought in by TF 2.0 if you would still like to follow the book's code and explanation 🙂
