### ISSUE TITLE
Please add requirements text file to this repo.

### ISSUE THREAD

**Issue by Rezwanul-Haque** [PacktPublishing/Hands-On-Python-Deep-Learning-for-Web#12]

**Comment by shubham763** [comment]
Hi @Rezwanul-Haque 

![image](https://user-images.githubusercontent.com/60926838/108679285-4a385900-7512-11eb-8728-60317ecc03dc.png)

Above is the software/hardware list, you can find this in the GitHub readme file. Apart from this if you want any other requirements file please do let us know, as there's no description given we're not sure which requirements text file you need.

Regards,
Shubham

**Comment by Rezwanul-Haque** [comment]
Hi @shubham763 

Thanks for replying to my query. Sorry If my question confuses you.

To run the code I need to know which python package version to use as sometimes packages updates and the previous version of the code not working in the latest package version.

This is an example of the requirements.txt

 Example:
 ```
 # requirements.txt 
 numpy==1.20.1
 matplotlib==3.3.4
 ```
 To create a virtual env, requirements.txt would be really helpful. So that what package version ex. Pandas, Keras, etc you use to write this repository's code.

**Comment by sayakpaul** [comment]
Each chapter tells you about the specific packages and their versions needed to run chapter code.
